name: Unzip and Commit

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Unzip and push
        run: |
          unzip "MedLinguaAI (1).zip" -d extracted
          rm "MedLinguaAI (1).zip"
          mv extracted/* ./
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Extracted and pushed"
          git push
